openapi: 3.0.3
info:
  title: Autosuggest API
  description: >-
    MapmyIndia Search APIs unleash the full potential of MapmyIndia Maps to provide users with ultimate location discoverability experience. It helps users explore our comprehensive & accurate map with over 50 million places mapped for India & its neighbouring nations. <br><br> The Autosuggest API helps users to complete queries faster by adding intelligent search capabilities to your web or mobile app. This API returns a list of results as well as suggested queries as the user types in the search field. This API also supports Hindi language. If a user enters query in hindi language he will get results in Hindi. <br><br> **Note**: <ol> <li> The response listed in the below documentation is ONLY indicative of the overall capabilities of MapmyIndia's Search APIs. </li><li> Not all response parameters mentioned in the below documentation is assured to be present in all the use-cases. The response of any of the below search API is thus, dependent on the use-case agreed upon between MapmyIndia & it's API consumer. </i><li> For any further clarifications on what all of the response structure is available for your use case, please contact your business relationship manager or contact MapmyIndia API support.</li><li> <strong>PREMIUM APIs/Parameters</strong> are not available for evalulation on signup. To get access, please contact API Support.</li></ol>
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/signup
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
security: 
  - BearerAuth: []
paths:
  /api/places/search/json:
    get:
      tags: 
        - Autosuggest API
      description: >-
        The Autosuggest API helps users to complete queries faster by adding intelligent search capabilities to your web or mobile app. This API returns a list of results as well as suggested queries as the user types in the search field. This API also supports Hindi language. If a user enters query in hindi language he will get results in Hindi.
        <p style=text-align:right><strong><a href="https://www.mapmyindia.com/api/advanced-maps/doc/sample/mapmyindia-vector-maps-auto-suggest-api-example.php">Live Demo</a> | <a href="https://github.com/MapmyIndia/mapmyindia-rest-api/tree/master/mapmyindia-maps-auto-suggest-api-example">Download Sample Code</a> </p>
      summary: >-
         AutoSuggest API
      operationId: AutoSuggestAPI
      parameters:
        # - name: Authorization
        #   in: header
        #   description: >-
        #     Authorization header with the value: “{token_type} {access_token}”. <br> Please generate your token from token generation API before calling this API.
        #   required: true
        #   allowEmptyValue: false
        #   schema:
        #     type: string
        #   example: "bearer 0XXXXXXf-dXX0-4XX0-8XXa-eXXXXXXXXXX6"
        - name: query
          in: query
          description: 'Enter the query on which the search has to be done.'
          required: true
          allowEmptyValue: false
          schema:
            type: string
          example: "mapmyindia"
        - name: location
          in: query
          description: 'Location is required to get location biased autosuggest results.'
          required: false
          allowEmptyValue: false
          example: "28.454,77.435"
          schema:
            type: string
        - name: region
          in: query
          description: 'It takes in the country code. LKA, IND, BTN, BGD, NPL for Sri-Lanka, India, Bhutan, Bangladesh, Nepal respectively. Default is India (IND).'
          example: "IND"
          required: false
          allowEmptyValue: false
          schema:
            type: string
        - name: tokenizeAddress
          in: query
          description: 'It is the valueless parameter provides the different address attributes in a structured object.'
          required: false
          allowEmptyValue: true
          schema:
            type: boolean
        - name: pod
          in: query
          description: 'It takes in the place type code which helps in restricting the results to certain chosen type.<br>
            Below mentioned are the codes for the pod:<br><ul>
            <li>SLC: Sublocality
            <li>LC: Locality
            <li>CITY: City
            <li>VLG: Village
            <li>SDIST: Subdistrict
            <li>DIST: District
            <li>STATE: State
            <li>SSLC: Subsublocality'
          required: false
          example: "CITY"
          schema:
            type: string
          allowEmptyValue: false
        - name: filter
          in: query
          description: 'This parameter helps you restrict the result either by mentioning a bounded area or to certain eloc (6 digit code to any poi, locality, city, etc.), below mentioned are the both types:<br><ul><li>filter = pin:It takes pincode/postal code of an area{e.g. filter=pin:110055}<li>filter = bounds lat1,lng1;lat2,lng2(latitude,longitude){e.g. filter=bounds 28.598882, 77.212407; 28.467375, 77.353513}<li>filter = cop {eloc} (string) {e.g. filter=cop:YMCZ0J}</ul>'
          required: false
          example: "pin:110001"
          allowEmptyValue: false
          schema:
            type: string
        - name: bridge
          in: query
          description: '(Valueless)It initiates a bridge to be created to provide applicable nearby API searches in the `suggestedSearches` response object.'
          required: false
          allowEmptyValue: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutosuggestAPIResults'
        '204':
          description: Not found
        '400':
          description: Bad request
        '401':
          description: API access denied
        '403':
          description: Forbidden
        '500':
          description: Something went wrong
        '503':
          description: Internal server error
      deprecated: false
      servers:
        - url: https://atlas.mapmyindia.com
          description: 'Live Prod server for OAuth 2 based APIs'
components:
  schemas:
    AutosuggestAPIResults:
      title: Autosuggest Results
      description: The result object which contains the Autosuggest API results.
      type: object
      required:
        - suggestedLocations
        - userAddedLocation
        - suggestedSearches
      properties:
        suggestedLocations:
          type: array
          items: 
            $ref: '#/components/schemas/AS1'
        userAddedLocation:
          type: array
          items:
            $ref: '#/components/schemas/AS2'
        suggestedSearches:
          type: array
          items:
            $ref: '#/components/schemas/AS3'
    AS1:
      title: Suggested Location
      type: object
      required:
        - type
        - typeX
        - placeAddress
        - latitude
        - longitude
        - eLoc
        - entryLatitude
        - entryLongitude
        - placeName
        - alternateName
        - keywords
        - p
        - distance
        - orderIndex
        - score
        - suggester
        - addressTokens
        - richInfo
      properties:
        type:
          type: string
          description: 'This is the type whether the results is POI or any building point.'
          format: string
          example: 'POI'
        typeX:
          type: integer
          description: 'Type attribute for internal use only for MapmyIndia.'
          format: integer
          example: 7
        placeAddress:
          type: string
          description: 'Address of the location.'
          format: string
          example: 'Yippee Rooms, Sector 56, Gurugram, Haryana, 122011'
        latitude:
          type: number
          description: 'It shows us the latitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        longitude:
          type: number
          description: 'It shows us the longitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        eLoc:
          type: string
          description: 'It is the Six or eight digit unique code offered only by mapmyindia to search for any address through this eLoc.'
          format: string
          example: '2LH9OC'
        entryLatitude:
          type: number
          description: 'It shows us the entry latitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        entryLongitude:
          type: number
          description: 'It shows us the entry longitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        placeName:
          type: string
          description: This shows the name of the POI
          format: string
          example: 'OYO Hotel'
        alternateName: 
          type: string
          description: 'This shows the alternate name of the POI'
          format: string
          example: 'OyoRooms,OYO 40400 Yippe Rooms,OYO Rooms Hotel'
        keywords:
          type: array
          description: 'The keywords/category codes associated with the given result.'
          items:
            $ref: '#/components/schemas/NB4'
        addressTokens:
          $ref: '#/components/schemas/NB3'
        p:
          type: integer
          description: 'This shows the priority of the POI'
          format: integer
          example: 11663
        orderIndex:
          type: integer
          description: 'This shows the order of the search results priority wise.'
          format: integer
          example: 1
        score:
          type: number
          description: 'This shows the score of the POI.'
          format: integer
          example: 1.5075794782130676
        suggester:
          type: string
          description: 'This shows on which basis the search results has been found.'
          format: string
          example: 'alternateName'
        richInfo:
          type: array
          description: This shows the rich info associated with the given result.
          items:
            type: object
          format: array of strings
          example: ''
    AS2:
      title: User Added Location
      description: 'The result object which contains the user added POI results.'
      type: object
      required:
        - eLoc
        - entryLatitude
        - entryLongitude
        - latitude
        - longitude
        - orderIndex
        - placeAddress
        - placeName
        - resultType
        - type
        - userName
      properties:
        eLoc:
          type: string
          description: 'It is the Six or eight digit unique code offered only by mapmyindia to search for any address through this eLoc.'
          format: string
          example: '2LH9OC'
        entryLatitude:
          type: number
          format: double
          example: 'RESTRICTED'
          description: 'latitude of the entrance of the location. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
        entryLongitude:
          type: number
          format: double
          example: 'RESTRICTED'
          description: 'longitude of the entrance of the location. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
        latitude:
          type: number
          description: 'It shows us the latitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        longitude:
          type: number
          description: 'It shows us the longitude of the location searched. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.'
          format: double
          example: 'RESTRICTED'
        orderIndex:
          type: integer
          description: 'This shows the order of the search results priority wise.'
          format: integer
          example: 1
        placeAddress:
          type: string
          description: 'This is the address of the text searched by you.'
          format: string
          example: 'Yippee Rooms, Sector 56, Gurugram, Haryana, 122011'
        placeName:
          type: string
          description: 'This shows the name of the POI.'
          format: string
          example: OYO Hotel
        resultType:
          type: string
          description: 'It Shows the the category of result falling into. For eg. UAP'
          format: string
          example: UAP
        type: 
          type: string
          format: string
          example: ''
        userName: 
          type: string
          description: 'It shows the UserID of the person who added the location.'
          format: string
          example: usr1577100139i799918080
    AS3:
      title: Suggested Search
      description: 'The result object which contains the Auto Suggest API Suggested results shows.'
      type: object
      required:
        - keyword
        - identifier
        - location
        - hyperlink
        - orderIndex
        - eLoc
      properties:
        keyword:
          type: string
          description: 'It shows the result keyword'
          format: string
          example: 'corona testing lab'
        identifier:
          type: string
          description: 'on what basis the results shown'
          format: string
          example: 'near'
        location: 
          type: string
          description: 'location near the results are shown'
          format: string
          example: 'me'
        hyperlink:
          type: string
          description: 'direct link of the poi.'
          format: string
          example: 'https://atlas.mapmyindia.com/api/places/nearby/json?explain&richData&username=atlasuser&refLocation=28.550592,77.26877&keywords=hsptst'
        orderIndex:
          type: integer
          description: 'This shows the order of the search results priority wise.'
          format: integer
          example: 0
        eLoc:
          type: string
          description: 'It is the Six or eight digit unique code offered only by mapmyindia to search for any address through this eLoc.'
          format: string
          example: 'null'
    NB3:
      title: tokenizeAddress
      description: >-
        It shows the admin details along with the house address. Address token information is NOT available in generic response; and is RESTRICTED.
      type: object
      required:
        - district
        - city
        - state
      properties:
        houseNumber:
          type: string
          description: House Number of the POI.
          format: string
          example: '237'
        houseName:
          type: string
          description: House Name of the POI.
          format: string
          example: 'MMI Building'
        poi:
          type: string
          description: Name of the POI.
          format: string
          example: 'MapmyIndia Head Office'
        street:
          type: string
          description: Name of the street.
          format: string
          example: ''
        subSubLocality:
          type: string
          description: Name of the subsublocality.
          format: string
          example: ''
        subLocality:
          type: string
          description: Name of the sublocality.
          format: string
          example: ''
        locality:
          type: string
          description: Name of the locality.
          format: string
          example: 'Okhla industrial phase 3'
        village:
          type: string
          description: Name of the village.
          format: string
          example: 'Okhla Vilage'
        subDistrict:
          type: string
          description: Name of the subDistrict.
          format: string
          example: ''
        district:
          type: string
          description: Name of the District.
          format: string
          example: 'South Delhi'
        city:
          type: string
          description: Name of the city.
          format: string
          example: 'New Delhi'
        state:
          type: string
          description: Name of the STATE.
          format: string
          example: 'Delhi'
        pincode:
          type: integer
          description: PINcode of the location.
          format: string
          example: '110010'
    NB4:
      title: Keywords
      type: object
      example: 'FINATM'
  securitySchemes:
    BearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: 'bearer 0XXXXXXf-dXX0-4XX0-8XXa-eXXXXXXXXXX6'