openapi: 3.0.3
info:
  title: Distance Matrix Predictive API
  description: >-
    **Note**: <ol> <li> The response listed in the below documentation is ONLY indicative of the overall capabilities of MapmyIndia's Search APIs. </li><li> Not all response parameters mentioned in the below documentation is assured to be present in all the use-cases. The response of any of the below search API is thus, dependent on the use-case agreed upon between MapmyIndia & it's API consumer. </i><li> For any further clarifications on what all of the response structure is available for your use case, please contact your business relationship manager or contact MapmyIndia API support.</li><li> <strong>PREMIUM APIs</strong> are not available for evalulation on signup. To get access, please contact API Support.</li></ol>
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/signup
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
servers:
  - url: https://apis.mapmyindia.com/advancedmaps/v1
    description: 'Live Prod server for Distance Matrix Predictive API'
paths:
  /{REST_KEY}/distance_matrix_predictive/driving/{coordinates}:
    get: 
      tags: 
        - Distance Matrix Predictive API
      description: >-
        This API computes the distance and duration of a route between a source/primary position (geographical coordinates) and a list of all supplied secondary positions. Optionally one can input the <code>dep_time</code> parameter and get the distance and duration optimized for that part of the day of a week. Time based functionality is available for selected cities only. Please note that maximum number of points are limited to 100 only including source and secondary positions.
        <p style=text-align:right><strong>PREMIUM API* </p>
      summary: Distance Matrix Predictive ETA API
      operationId: dmPAPI
      parameters: 
        - name: REST_KEY
          in: path
          description: 'The REST API licence key allocated to you by signing into our services and registering yourself as a developer.'
          allowEmptyValue: false
          required: true
          example: "threstapikeywillcomeheretoaccess"
          schema:
            type: string
        - name: coordinates
          in: path
          description: >-
            Coordinates are pair of <strong>comma separated longitude & latitude</strong> values. First coordinate will be consider as start point (mandatory); a last coordinate will be considered as end point (mandatory) and those in between are via points (optional). <br>Example: {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] (part of URL).
          allowEmptyValue: false
          required: true
          example: "77.131123,28.552413;77.113091,28.544649"
          schema:
            type: string
        - name: dep_time
          in: query
          description: >-
            the UNIX timestamp of departure in seconds. Distance and ETA will be optimized as per given time.
          allowEmptyValue: false
          schema:
            type: integer
          required: false
          example: 1531543500
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/distanceMatrixPredictive'
          '204':
            description: DB Connection error.
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '404':
            description: Not found
          '412':
            description: Precondition Failed, i.e. Some existing pre-condition in formulating a valid API request was not fulfilled.
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
      deprecated: false
components: 
  schemas: 
    DMresults: 
      title: dm results
      description: 'dm results'
      type: object
      required: 
        - distances
        - code
        - durations
      properties:
        code: 
          type: string
          title: 'dmCode'
          description: >-
             if request is successful, response is ‘ok’. Else, see the service dependent and general status codes as available in the enum. <br>In case of error, “NoRoute” code is supported (in addition to the general ones) which means “no route found”. <br> <ul><li><code>Ok</code>: Request could be processed as expected.</li><li><code>InvalidUrl</code>: URL string is invalid.</li><li>InvalidService: Service name is invalid.</li><li><code>InvalidVersion</code>: Version is not found.</li><li><code>InvalidOptions</code>: Options are invalid.</li><li><code>InvalidQuery</code>: The query string is synctactically malformed.</li><li><code>InvalidValue</code>: The successfully parsed query parameters are invalid.</li><li><code>NoSegment</code>: One of the supplied input coordinates could not snap to street segment.</li><li><code>TooBig</code>: The request size violates one of the service specific request size restrictions.</li><li><code>NoRoute</code>: Means No Route Found.</li></ul>
          format: string
          example: "Ok"
        distances: 
          description: >-
            array of float distances in metres.
          type: array
          items: 
            example: [14076.1, 30927.6]
        durations: 
          description: >-
            array of float durations in seconds.
          type: array
          items: 
            example: [1884.9, 2644.1]
    distanceMatrixPredictive: 
      title: dmp object
      description: 'dmp object'
      type: object
      required: 
        - check
        - version
        - results
        - responseCode
      properties:
        check: 
          type: string
          title: 'check'
          description: >-
             internal response (for MMI internal purposes only)
          format: integer
          example: 5025
        version: 
          type: string
          title: 'version'
          description: >-
             API’s version information.
          format: string
          example: "250.19.5222"
        responseCode:
          type: string
          title: 'responseCode'
          description: >-
             See the service dependent and general status codes
          format: string
          example: "200"
        results:
          $ref: '#/components/schemas/DMresults'