openapi: 3.0.3
info:
  title: Snap to Road API
  description: >-
    **Note**: <ol> <li> The response listed in the below documentation is ONLY indicative of the overall capabilities of MapmyIndia's Search APIs. </li><li> Not all response parameters mentioned in the below documentation is assured to be present in all the use-cases. The response of any of the below search API is thus, dependent on the use-case agreed upon between MapmyIndia & it's API consumer. </i><li> For any further clarifications on what all of the response structure is available for your use case, please contact your business relationship manager or contact MapmyIndia API support.</li><li> <strong>PREMIUM APIs</strong> are not available for evalulation on signup. To get access, please contact API Support.</li></ol>
  termsOfService: 'https://www.mapmyindia.com/api/terms-&-conditions'
  version: 1.0.0
  license:
    name: MapmyIndia License Key Signup
    url: https://www.mapmyindia.com/api/signup
  contact:
    name: MapmyIndia API Support
    email: apisupport@mapmyindia.com
    url: https://www.mapmyindia.com/api/
servers:
  - url: https://apis.mapmyindia.com/advancedmaps/v1
    description: 'Live Prod server for Snap to Road API'
paths:
  /{REST_KEY}/snapToRoad:
    post: 
      tags: 
        - Snap to Road API
      description: >-
        Snap-To-Road API, snaps given GPS points to the road network in the most plausible way. Maximum number of points are limited to 100 only. Our USP is to take GPS points collected along a route and return a similar set of corrected & aligned data with the points matched to the road with our intelligent Snap To Road API.<br>
        Now seamlessly calculate accurate distances from points which follow the geometry of the road & show accurate positions on map. This API provides a critical feature that is immensely valuable when tracking assets and for data analytics of path traversed by vehicle, people or assets.
        <br><br><strong>Note</strong>: <ol><li>The request might result multiple sub-traces.</li><li>Large jumps in the timestamps (> 60s) or improbable transitions lead to trace splits if a complete matching could not be found.</li><li>The algorithm might not be able to match all points. Outliers are removed if they cannot be matched successfully.</li></ol>
        <p style=text-align:right><strong><a href="https://www.mapmyindia.com/api/advanced-maps/doc/sample/mapmyindia-maps-snaptoroad-example">Live Demo</a></p>
      summary: Snap to Road API
      operationId: snapToRoadAPI
      parameters: 
        - name: REST_KEY
          in: path
          description: 'The REST API licence key allocated to you by signing into our services and registering yourself as a developer.'
          allowEmptyValue: false
          required: true
          example: "threstapikeywillcomeheretoaccess"
          schema:
            type: string
      requestBody: 
        content:
          'application/x-www-form-urlencoded':
            schema:
             properties:
                pts: 
                  description: >-
                    Coordinate is pair of comma separated longitude & latitude value, First coordinate will be consider as start point; a last coordinate will be as end points and between are via points; like {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...]. At present maximum number of points are limited to 100 in a single request.
                  type: string
                  example: "78.40573,17.37317;78.40958,17.37314;78.41845,17.37449;78.409992,17.37328;78.420460,17.377443;78.421350,17.380200"
                timestamps:
                  description: >-
                    Timestamps for the input locations in seconds since UNIX epoch. Timestamps need to be monotonically increasing. Values must be integer {timestamp};{timestamp};{timestamp} ...
                  type: string
                  example: "1527056019;1527056020;1527056021;1527056022;1527056023;1527056024"
                geometries: 
                  description: >-
                    This parameter used to change the route geometry format/density (influences overview and per step). Default value is <code>polyline</code> with 5 digit precision; <code>polyline6</code> for 6digit precision; <code>geojson</code> for geometries as geojson. Please note that “timestamps” parameter is mandatory for enabling geometries.
                  type: string
                  example: "polyline"
                radiuses: 
                  description: >-
                    Standard deviation of GPS precision used for map matching. If available use GPS accuracy in meters. Default value is 5 metres. Values must be integer {radius};{radius};{radius} ...
                  type: string
                  example: "50;50;50;50;50;50"
                region: 
                  description: >-
                    This parameter is optional for India; for other countries (Sri Lanka, Nepal, Bangladesh & Bhutan) this parameter is mandatory. Possible values are ind (for India, default), lka (for Sri Lanka) , npl (for Nepal) , bgd (for Bangladesh), mmr (for Myanmar) and btn (for Bhutan)
                  type: string
                  example: "IND"
             required:
               - pts
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/snapToRoad'
          '204':
            description: DB Connection error.
          '400':
            description: Bad request
          '401':
            description: API access denied
          '403':
            description: Forbidden
          '404':
            description: Not found
          '412':
            description: Precondition Failed, i.e. Some existing pre-condition in formulating a valid API request was not fulfilled.
          '500':
            description: Something went wrong
          '503':
            description: Internal server error
      deprecated: false
components: 
  schemas: 
    snapToRoad: 
      title: snap to road object
      description: 'snap to road object'
      type: object
      required: 
        - Server
        - version
        - results
        - responseCode
      properties:
        Server: 
          type: string
          title: 'Server'
          description: >-
             Gives Information on active service's server.
          format: string
          example: "Adv-5400"
        version: 
          type: string
          title: 'version'
          description: >-
             API’s version information.
          format: string
          example: "250.19.5222"
        responseCode:
          type: string
          title: 'responseCode'
          description: >-
             See the service dependent and general status codes
          format: string
          example: "200"
        results:
          $ref: '#/components/schemas/snapRoRoadResults'
    snapRoRoadResults: 
      title: snap to road results
      description: 'snap to road results'
      type: object
      required: 
        - snappedPoints
        - matchings
      properties:
        snappedPoints: 
          description: >-
            Array of Waypoint objects representing all points of the trace in order. If the trace point was omitted by map matching because it is an outlier, the entry will be null.
          type: array
          items:
              $ref: '#/components/schemas/snappedPoints'
        matchings: 
          description: >-
            An array of Route objects that assemble the trace.
          type: array
          items:
              $ref: '#/components/schemas/matchings'
    matchings: 
      title: snap to road matchings
      description: 'snap to road matchings'
      type: object
      required: 
        - geometry
      properties:
        geometry: 
          description: >-
            Returns the whole geometry of the route as per given parameter ‘geometries’ default is encoded ‘polyline’ with 5 digit accuracy for positional coordinates. Geometry information is NOT available in most use-case driven response; and is RESTRICTED.
          type: string
          example: "ie`iByrp}MN{HKeMXmOKuGq@}JaBaHaDmIgB{BuDcCuGeBeP{D"
    snappedPoints: 
      title: snap to road snapped points
      description: 'snap to road snapped points'
      type: object
      required: 
        - location
        - distance
        - waypoint_index
      properties:
        location: 
          type: array
          items: 
            type: string  
          title: 'matchedCoordinates'
          description: >-
             Location of Matched point (Longitude, Latitude)
          example: [77.113089,28.544643]
        distance: 
          type: number
          title: 'snappingDistanceSnap-To-Road'
          description: >-
             Distance from the snapped point.
          format: number
          example: 4.014843
        waypoint_index: 
          type: number
          title: 'snappingDistanceSnap-To-Road'
          description: >-
             Distance from the snapped point.
          format: integer
          example: 0